# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Ruben Baraut Gamez
subtitle: Software Enginner / Web developer
my_name: Ruben Baraut Gamez
my_full_name: Ruben Baraut Gamez

google_analytics_tracking_id: UA-70760309-1
disqus_shortname: rubenbaraut
