sculpin_content_types:
    posts_tecnologics:
          type: path
          path: _posts_tecnologics
          permalink: :year/:month/:day/:slug_title/
          layout: default
          enabled: true
          taxonomies:
              - tags
              - categories
    posts_culinaris:
          type: path
          path: _posts_culinaris
          permalink: :year/:month/:day/:slug_title/
          layout: default
          enabled: true
          taxonomies:
              - tags
              - categories